### ISSUE TITLE
write certificate to openpgp applet

### ISSUE THREAD

**Issue by Exordian** [Yubico/ykneo-openpgp#16]
gnupg has a hidden command called "writecert/readcert 3" to write certificates to the openpgp card

i've tried that w/ the yubikey applet

```
gpg/card> writecert 3 < /tmp/1024.der
gpg: error writing certificate to card: object is too big
```

is this supported at all atm? if not, is it planned to? since storing certificates on a yubikey neo should be possible with opensc/piv applet anyway

since most smartcard vendors only ship their driver with CAL's (Client Access Licenses)  using smartcards in coperate enviroments is very expensive
there is already an opensource openpgp card driver which works with the yubikey neo (at least it's correctly detected by windows as an openpgp card)
http://www.mysmartlogon.com/products/openpgp-card-mini-driver.html
it would be still impossible to directly enroll to the openpgp applet but it would be a nice feature anyway to support that

**Comment by omnihil0** [comment]
Is there a way to adjust this? There is no way to fit an X509v3 certificate with 4096bit RSA issuer and subject in 1.2k. 2k would be enough.
