### ISSUE TITLE
Externally created Secret keys don't get imported after resetting Applet

### ISSUE THREAD

**Issue by grince** [Yubico/ykneo-openpgp#24]
Hi,

I already explained my situation in [url]http://forum.yubico.com/viewtopic.php?f=26&t=1710&p=6741#p6741[/url].
My main concern is: Have I done something wrong or do I try to copy the wrong keys? or is this really a bug?

Greetings, Rince

**Comment by klali** [comment]
Importing keys to the card is only supported from gpg 2.0.22 and later, you seem to be using gpg 2.0.17

/klas
