### ISSUE TITLE
Incorrect applet version reported by YubiKey NEO Manager

### ISSUE THREAD

**Issue by bmalkow** [Yubico/ykneo-openpgp#26]
Not sure if this is problem of openpgp applet or rather YubiKey NEO Manager:

    gpg-connect-agent --hex "scd apdu 00 f1 00 00" /bye
    D[0000]  01 00 11 90 00                                     .....           
    OK

what looks ok. But YubiKey NEO Manager shows: "1.0.17 installed"

**Comment by dainnilsson** [comment]
I'm not sure if this version number is supposed to be BCD or not. If it isn't, then the applet is wrong (0x11 is 17 in decimal). If it is, then that should probably be stated somewhere in the documentation. I'm not sure why it would be BCD though.

**Comment by bmalkow** [comment]
No idea. Command F1 is vendor specific, so you should decide ;-)

**Comment by dainnilsson** [comment]
Yeah, I'm waiting for @klali to comment, as he is the one who bumped the version ;)

**Comment by klali** [comment]
Hello,

Yes. The version number is BCD (since it's recommended to read it with gpg-connect-agent in a number of places).

/klas

**Comment by dainnilsson** [comment]
As that's settled I'm updating the NEO manager to treat this value as BCD so that it displays correctly.
