### ISSUE TITLE
Release 1.0.10?

### ISSUE THREAD

**Issue by jonathancross** [Yubico/ykneo-openpgp#35]
According to [SecurityAdvisory 2015-04-14](https://developers.yubico.com/ykneo-openpgp/SecurityAdvisory%202015-04-14.html) all versions of this OpenPGP applet `1.0.9` or earlier are vulnerable.  There is a tag for `1.0.10`, but no [official release](https://github.com/Yubico/ykneo-openpgp/releases) on GitHub since [1.0.2](https://github.com/Yubico/ykneo-openpgp/releases/tag/1.0.2). 

Also, the security fix should be clearly explained in the release notes as it is not obvious from commit comments.

**Comment by klali** [comment]
Official releases for this project is listed on https://developers.yubico.com/ykneo-openpgp/Releases/ unfortunately the github releases tab can't be disabled.
