### ISSUE TITLE
No support for 4096bit keys

### ISSUE THREAD

**Issue by zephyia** [Yubico/ykneo-openpgp#42]
According to the website YubiKey4 and Yubikey4nano have support for 4096bit RSA keys, however looking at this code there is no way that could be true - the key size is PGPKey isn't big enough. That tells me there is probably some code lying around somewhere that is being loaded onto Yubikey4's that hasn't been synced with this repository?

There reason I'm looking at this is that I have a YubiKey4nano and am having issues loading a 4096 bit key onto it using GPG - I am willing to try and edit this code myself (Im sure its more than just modifying the constants though - so any pointers would be appreciate (or the code for the yubikey4 uploaded somewhere?) - or some other fix?

**Comment by asayler** [comment]
This repo only applies to the Yubikey Neo. The Yubikey4 line of devices run proprietary closed-source code, not the code contained here. See the following for details:

https://www.yubico.com/2016/05/secure-hardware-vs-open-source/
https://plus.google.com/+KonstantinRyabitsev/posts/4a7RNxtt7vy

**Comment by zephyia** [comment]
Thanks, this makes sense with what I am seeing. I have a support ticket open and they are assisting me with working out the issue with the YubiKey4. Thanks for the speedy response.

**Comment by jonathancross** [comment]
In case it was not 100% clear, the YubiKey NEO only supports key sizes up to 2048, not 4096.
Only the YubiKey 4 (not open source) supports the larger keys.
